### ISSUE TITLE
MS4: Business Questions

### ISSUE THREAD

**Issue by luisfelipedussan** [ISIS3510-202410-Team25/Wiki#6]
We need to fix the business questions, including the why of them. And follow the feedback guidelines. remove type 1 second question. read feedback and fix the errors

**Comment by l-villamil** [comment]
update the BQ with the VD map. and do a justifcation of each BQ

**Comment by luisfelipedussan** [comment]
We sent a forms because we did not agreed on last sprints, also we made some corrections
